### ISSUE TITLE
Got an unexpected error when tried to exit the page with the Dropdown widget.

### ISSUE THREAD

**Issue by boschprv** [Khongchai/modular_customizable_dropdown#1]
`#0 _ModularCustomizableDropdownState._precalculateDropdownHeight (package:modular_customizable_dropdown/widgets/ dropdown.dart:397:37)`

**Comment by Khongchai** [comment]
Thanks for opening this issue. I have already resolved the problem -- it's due to a deferred rendering wiith addPostFrameCallback. I was trying to use a defunct context of the Offstage dropdown after the dropdown has already been dismissed (we also dismiss the Offstage widget). I will be deploying the new version soon.
